version: "3.9"

services:

  weather-service:
    build:
      context: ./weather-service
    platform: linux/arm64
    container_name: weather-service
    ports:
      - "8001:8000"
    volumes:
      - ./weather-service:/app
    environment:
      - DEBUG=1

  seismic-service:
    build:
      context: ./seismic-service
    platform: linux/arm64
    container_name: seismic-service
    ports:
      - "8002:8000"
    volumes:
      - ./seismic-service:/app
    environment:
      - DEBUG=1

  ocean-service:
    build:
      context: ./ocean-service
    platform: linux/arm64
    container_name: ocean-service
    ports:
      - "8003:8000"
    volumes:
      - ./ocean-service:/app
    environment:
      - DEBUG=1

  user-service:
    build:
      context: ./user_service
    platform: linux/arm64
    container_name: user-service
    ports:
      - "8004:8000"
    volumes:
      - ./user_service:/app
    environment:
      - DEBUG=1
    depends_on:
      - db
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  risk-engine:
    build:
      context: ./risk_engine
    platform: linux/arm64
    container_name: risk-engine
    ports:
      - "8005:8000"
    volumes:
      - ./risk_engine:/app
      - /app/node_modules
    depends_on:
      - weather-service
      - seismic-service
      - ocean-service
      - user-service

  db:
    image: postgres:15-alpine
    container_name: disaster-db
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 10 &&
      ollama pull qwen3:1.7b &&
      wait
      "

volumes:
  postgres_data:
  ollama: